"""
Schema definitions for evidence types.
"""
from .common import (
    EvidenceSource,
    EventType,
    RefType,
    PRAction,
    IssueAction,
    WorkflowConclusion,
    IOCType,
    GitHubActor,
    GitHubRepository,
    VerificationInfo,
    VerificationResult,
    AnyEvent,
    AnyObservation,
    AnyEvidence,
)
from .events import (
    Event,
    CommitInPush,
    PushEvent,
    PullRequestEvent,
    IssueEvent,
    IssueCommentEvent,
    CreateEvent,
    DeleteEvent,
    ForkEvent,
    WorkflowRunEvent,
    ReleaseEvent,
    WatchEvent,
    MemberEvent,
    PublicEvent,
)
from .observations import (
    Observation,
    CommitAuthor,
    FileChange,
    CommitObservation,
    IssueObservation,
    FileObservation,
    ForkObservation,
    BranchObservation,
    TagObservation,
    ReleaseObservation,
    WaybackSnapshot,
    SnapshotObservation,
    IOC,
    ArticleObservation,
)

__all__ = [
    # Enums
    "EvidenceSource",
    "EventType",
    "RefType",
    "PRAction",
    "IssueAction",
    "WorkflowConclusion",
    "IOCType",
    # Common models
    "GitHubActor",
    "GitHubRepository",
    "VerificationInfo",
    "VerificationResult",
    # Type aliases
    "AnyEvent",
    "AnyObservation",
    "AnyEvidence",
    # Events
    "Event",
    "CommitInPush",
    "PushEvent",
    "PullRequestEvent",
    "IssueEvent",
    "IssueCommentEvent",
    "CreateEvent",
    "DeleteEvent",
    "ForkEvent",
    "WorkflowRunEvent",
    "ReleaseEvent",
    "WatchEvent",
    "MemberEvent",
    "PublicEvent",
    # Observations
    "Observation",
    "CommitAuthor",
    "FileChange",
    "CommitObservation",
    "IssueObservation",
    "FileObservation",
    "ForkObservation",
    "BranchObservation",
    "TagObservation",
    "ReleaseObservation",
    "WaybackSnapshot",
    "SnapshotObservation",
    "IOC",
    "ArticleObservation",
]
